sudo: false
language: c
compiler: clang
addons:
  apt:
    packages:
    - libgmp-dev
    - build-essential
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack --no-terminal --install-ghc test
cache:
  directories:
  - "$HOME/.stack"
deploy:
  provider: hackage
  username: Thierry
  password:
    secure: Pe2+9TtuECliQ/9BiLCuupw5csjG6LhoUbDBA6wUqeeKiAgwkP05CXU+vmrHp4MNqXoqAojEcOLxZcDcK+8lIRZNZY1t2hsEc/FdTXX1t3ugpaH8trZozCDaB6fCr6LPCjAdZg8kgOLv9w3LpyipDY0unQ16SEa3nscHgjDKpeJIVIQo0rvLAPXFO6lBnU/XLkOckh7kqhpIygu3MxNKDnJePQCW1KTC6zrazniioEjrHbrtTKjMwXK7BLbV6uLFhW7jKn6LZMqK3dBsJU0SAf7K2QhfUjJ7FlnQdEY0hNVT+VkuOjzjDN1PdzxhaeFA3O7B8TYKm2fVlW5vtn+wsYFp170mcJW7fidZFqsuNHD/h+Dv/NzjxD8H4ZPgZ1OUUIBSv4kDQI1XzuGiWp3m7qHVeqHadovnKKHA9PLfaoL7gQ513D8TahWhWpjXsX5FUxfNtyMwO+MysdBMbMQVHSV4WJ3O/KpBtt1hJd2trHWiWc1xt4+ZdVcq4Jzv9KMPiFH4g/qPwHpWMRT4M6oP6mfI+0VXxh90G3/ROHn5fi+IF2u5MpwgFuWVnmQpkrE+UfYSeUyvVO5DNp1jNc4OLZWvptgJOTm1VMXFHuXU2mN8qZDFacjbCqyhvGdki+oi/5TNwgueElGf/RpWQwVrfQL06DN+BkJrYczyhYIOTV8=
  skip_cleanup: true
  on:
    repo: fpinsight/heatshrink
    tags: true
notifications:
  slack:
    secure: kDf4OzwSSje0iVf4/PLKaplU5XooAJXZMlrBP+fppdRWvwiAFeJiw50U8fq1dT2Y/IsiD1Kjncul/J0kNW1OPkjetpg2OuJDMSpdI2i5SouJdHi4K5AX7ewk2yg2TMUDlcLOYzl8nALJvIo1rYY9GFL1FjxKNZD11ne/WXG8MbWjCqtszXtxulmGWIIrYfftGkh2Xi/0gOzwNaxtJOIc/FSko2jD9bVx2kSM2HUH9BsltOG2B2r9AyPvtxqNQmDSGyvuNHIKOsBCDc3N9V3YhBOULkmZ/6GZOZoZONP1qQ7NLYu2+nNu5PonO2MOVd0PQ5xonJWOhPVn7RDAG2j+T6EoMVlTE6rfSUymuRMBzYFrEJh46Tm6H5OpC5J15v49FhgnHfBezaWdFUEQp9iJ7ExyphR8QU16g3R1uXRoOoM7LqAhFiymESC0DF5cfdTaJQU2bGGmwFEgRc66jGsLbSY+Tt4aUEYSFwA2OC53Xagogn92rXtx1AMz5y6UEhacJxh+HLKyfy0wLVTX+FOwdGOHVhaD3GZxbmYAih348lfz5JyhyPh8MroD3nqrInx1hS0jXpbvHgrbeXmoi7aDqv2SPx8/vGNq74KaBOdIuq7Y1kTwoYFM5pr++tamQITvouZ9terJvtcjReImhX6L23Xavr07jgzhvOPWmoT2xl0=
